language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
script: 
  - ant -file com.java/build.xml
  
after_success:
  - mvn clean test jacoco:report 
  - bash <(curl -s https://codecov.io/bash)
  - f com.java/target/reports/jacoco.xml
 
