language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
    - sudo apt-get install python python-pygame python-pip python-imaging python-six python-netifaces git
    - sudo pip install pytmx
    - sudo pip install neteria
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tuxemon.py
