language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
script: 
  - ant -file witsiemon/build.xml
  - "mvn cobertura:cobertura"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report
